### ISSUE TITLE
Sidebar Configuration isn't actually doing anything?

### ISSUE THREAD

**Issue by silicon-academy** [elchininet/custom-sidebar#117] opened 2024-08-13 02:26 UTC
I have installed via HACS, and added to configuration.yaml:
``` 
frontend:
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar-yaml.js?v4.6.0 
 ```

I've also added a file at /config/www/sidebar-config.yaml
```
title: Home Assistant
order:
  - item: overview
    order: 0
  - new_item: true
    item: Frigate
    href: "/ccab4aaf_frigate-proxy/ingress"
    icon: mdi:camera
    order: 1
  - new_item: true
    item: Energy
    # href: "/energy"
    icon: mdi:lightning-bolt
    order: 2
  - new_item: true
    item: Automations
    href: "/config/automation"
    icon: mdi:robot
    order: 3
  - item: history
    icon: mdi:history
    order: 4
  - item: hacs
    order: 5
    notification: '[[[ state_attr("sensor.hacs", "repositories").length || "" ]]]'
  - item: config
    bottom: true
    order: 6
  - new_item: true
    item: Server Controls
    href: "/config/server_control"
    icon: mdi:server
    bottom: true
    order: 7
  - item: logbook
    bottom: true
    order: 8
  - new_item: true
    item: Logs
    bottom: true
    href: "/config/logs"
    icon: mdi:math-log
    order: 9
  - item: developer tools
    name: Dev tools
    icon: mdi:tools
    bottom: true
    order: 10
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: map
    hide: true
  - item: energy
    hide: true
  - item: media browser
    hide: true
```

I've restarted HA, cleared cache, and reloaded yaml, but nothing seems to be happening, and the original sidebar is still there. Is there something I'm doing wrong? I appreciate your help in advance, and this seems like a great repo. I apologize if I'm missing something, or if my English is bad, as it's not my first language. Thanks!

**Comment by elchininet** [comment] 2024-08-13 06:43
Hi @silicon-academy,

Open your Home Assistant instance in a browser and then check the developer console:

* Check that the `custom-sidebar` console info is there
* Look for any warning/error related to `custom-sidebar`

Regards

**Comment by silicon-academy** [comment] 2024-08-13 12:42
This is what it shows:
![image](https://github.com/user-attachments/assets/da631795-6e78-4fb0-8b0a-0eba1641ba29)

**Comment by elchininet** [comment] 2024-08-13 13:34
That is weird, in the first screenshot the console info is there, that means the the plugin is being loaded. In the second, there is an error that is only triggered if the plugin was not loaded, and that doesn‘t make any sense.

Could yo try to search for `custom-sidebar` on the `Elements` tab in your dev console and check how many matches do you get?

**Comment by silicon-academy** [comment] 2024-08-13 18:32
I figured it out, it was an error in my sidebar-config. It now works well on desktop. However, it's still the same with the android mobile app. I tried clearing the cache and force stopping, but it's still not working correctly. Any advice there? By the way, thanks for your help on this.

**Comment by elchininet** [comment] 2024-08-13 19:51
@silicon-academy,

Glad to hear that.

About the App, caching is sometimes hard to clean. Try to add another version at the end of the `extra_module_url` and restart Home Assistant.

But just a tip, because maybe there is another error in the config that is only happening on the App, begin with a simple config with just one item, if it works then start to add things one by one, but avoid a complex configuration at this moment, because if something fails in the App, it is very hard to detect where the issue is.

Regards

**Comment by silicon-academy** [comment] 2024-08-15 19:20
Yeah, sorry I've been out for a few days. I did realize that it only worked in chromium browsers, and I had to change the config to get it to work on Firefox and mobile browsers. It works on mobile Google Chrome and Samsung internet, but still no luck with the app.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by elchininet** [comment] 2024-08-15 20:01
What did you need to change? I have it working in all the green browsers and on IOS and Android. Did you try with a simple config just changing the name of one item?

Try to see if it works with a new user in the App, if that is the case, logout from the App and login again (it is a hassle but sometimes is the only way to make the App remove completely the cache).

**Comment by silicon-academy** [comment] 2024-08-15 20:12
There were just some config issues from the example I copied over, like media instead of media browser. That fixed it for all desktop and mobile browsers. I'll try logging in and out of the app, thanks for your advice.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by elchininet** [comment] 2024-08-15 20:45
>There were just some config issues from the example I copied over, like media instead of media browser.

Yes, the example is just an example to begin with and only in English. If someone doesn't have those items or their Home Assistant is in another language, they will receive a warning about the missing items but the plugin should still work for the items that match.

>I'll try logging in and out of the app, thanks for your advice.

Let me know how it goes, I had issues before with te App an another plugin that I mainatin I I needed to start over to get it work. I am letting this issue open, let me know the results of your tests.

Regards

**Comment by silicon-academy** [comment] 2024-08-16 02:16
Yup, I signed into home assistant from a different phone and the sidebar works perfectly. I guess I just have to log out and back in. Thanks for your help on this and your maintenance of this project!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by elchininet** [comment] 2024-08-20 19:16
Hi @silicon-academy,
Closing this one, if you have some issue related to the plugin code don't hesitate to open a new one.
Regards 👍🏼

**Closed** 2024-08-20 19:16 UTC
